force-app/main/default/objects/DmlOperation__c/DmlOperation__c.object-meta.xml
<CustomObject>
    <description>Records of DML operations for objects where tracking is enabled</description>
    <label>DML Operation</label>
    <nameField>
        <displayFormat>DO-{00000000}</displayFormat>
        <label>DML Operation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DML Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DmlOperation__c/fields/NumberOfRecords__c.field-meta.xml
<CustomField>
    <fullName>NumberOfRecords__c</fullName>
    <label>Num Records</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/DmlOperation__c/fields/SobjectName__c.field-meta.xml
<CustomField>
    <fullName>SobjectName__c</fullName>
    <description>The full API name of the Salesforce object</description>
    <inlineHelpText>The full API name of the Salesforce object</inlineHelpText>
    <label>Object API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DmlOperation__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>insert</fullName>
            </value>
            <value>
                <fullName>update</fullName>
            </value>
            <value>
                <fullName>delete</fullName>
            </value>
            <value>
                <fullName>undelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DmlHistoryService.cls
global class DmlHistoryService {

    global DmlHistoryService() {
        /* Nothin' to see here */
    }

    global static DmlHistoryService getInstance() {
        return new DmlHistoryService();
    }

    global Id trackDelete(List<SObject> records) {

        // Initialize the Delete Operation record
        DmlOperation__c op = new DmlOperation__c(
            NumberOfRecords__c = records.size(),
            SobjectName__c = DmlHistoryUtil.getSobjectName(records),
            Type__c = DmlHistoryUtil.DELETE_TYPE
        );

        // Create the record and remember the ID
        insert op;

        // Create the Salesforce File version
        ContentVersion version = DmlHistoryUtil.newContentVersion(
            DmlHistoryUtil.DELETE_OPERATION_TITLE,
            records
        );

        insert version;

        // Link the content document to the record
        insert DmlHistoryUtil.newContentDocumentLink(
            [
                SELECT
                    ContentDocumentId,
                    Id
                FROM ContentVersion
                WHERE Id = :version.Id
            ].ContentDocumentId,
            op.Id
        );

        // Return the Delete Operation ID
        return op.Id;
    }
}