force-app/main/default/objects/DmlOperation__c/DmlOperation__c.object-meta.xml
<CustomObject>
    <description>Records of DML operations for objects where tracking is enabled</description>
    <label>DML Operation</label>
    <nameField>
        <displayFormat>DO-{00000000}</displayFormat>
        <label>DML Operation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DML Operations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/DmlOperation__c/fields/SobjectName__c.field-meta.xml
<CustomField>
    <fullName>SobjectName__c</fullName>
    <description>The full API name of the Salesforce object</description>
    <inlineHelpText>The full API name of the Salesforce object</inlineHelpText>
    <label>Object API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DmlOperationSubject__c/DmlOperationSubject__c.object-meta.xml
<CustomObject>
    <description>The primary subject (i.e., record) of a DML operation</description>
    <label>DML Operation Subject</label>
    <nameField>
        <displayFormat>DOS-{00000000}</displayFormat>
        <label>DML Operation Subject Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DML Operation Subjects</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/DmlOperationSubject__c/fields/DmlOperation__c.field-meta.xml
<CustomField>
    <fullName>DmlOperation__c</fullName>
    <description>The DML operation which operated on this subject</description>
    <inlineHelpText>The DML operation which operated on this subject</inlineHelpText>
    <label>DML Operation</label>
    <referenceTo>DmlOperation__c</referenceTo>
    <relationshipLabel>DML Operation Subjects</relationshipLabel>
    <relationshipName>DmlOperationSubjects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/DmlOperationSubject__c/fields/DmlOperationType__c.field-meta.xml
<CustomField>
    <fullName>DmlOperationType__c</fullName>
    <description>The Type value from the parent DML Operation record</description>
    <inlineHelpText>The Type value from the parent DML Operation record</inlineHelpText>
    <label>DML Operation Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DmlOperationType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/DmlOperationSubject__c/fields/SubjectId__c.field-meta.xml
<CustomField>
    <fullName>SubjectId__c</fullName>
    <description>The Salesforce ID or record ID of the subject</description>
    <inlineHelpText>The Salesforce ID or record ID of the subject</inlineHelpText>
    <label>Subject ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/DmlOperationType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>insert</fullName>
    </customValue>
    <customValue>
        <fullName>update</fullName>
    </customValue>
    <customValue>
        <fullName>delete</fullName>
    </customValue>
    <customValue>
        <fullName>undelete</fullName>
    </customValue>
    <masterLabel>DML Operation Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/DmlHistoryServiceTest.cls
@isTest
private class DmlHistoryServiceTest {

    @isTest
    private static void trackDeleteAsyncApexJob() {

        // Given
        AsyncApexJob record = new AsyncApexJob();

        DmlHistoryService dmlHistory = new DmlHistoryService();

        // When
        Test.startTest();

        Id dmlOperationId = dmlHistory.trackDelete(
            new List<SObject> { record }
        );

        // Then
        Test.stopTest();

        System.assertNotEquals(
            null,
            dmlOperationId,
            Schema.SObjectType.DmlOperation__c.fields.Id.label
        );
    }

    @isTest
    private static void trackDeleteAccountsWithRecordIds() {

        // Given
        Account one = new Account(Name = 'One (Test)');

        Account two = new Account(Name = 'Two (Test)');

        List<Account> accounts = new List<Account> {
            one,
            two
        };

        insert accounts;

        // When
        Test.startTest();

        Id dmlOperationId = DmlHistoryService.getInstance().trackDelete(
            accounts,
            true
        );

        // Then
        Test.stopTest();

        List<DmlOperationSubject__c> subjects = [
            SELECT
                DmlOperationType__c,
                Id,
                SobjectName__c,
                SubjectId__c
            FROM DmlOperationSubject__c
            WHERE DmlOperation__c = :dmlOperationId
        ];

        // Assert expected subject values while compiling set of subject IDs
        Set<Id> subjectIdSet = new Set<Id>();

        for (DmlOperationSubject__c eachSubject : subjects) {
            subjectIdSet.add(eachSubject.SubjectId__c);

            System.assertEquals(
                'delete',
                eachSubject.DmlOperationType__c,
                Schema.SObjectType.DmlOperationSubject__c.fields.DmlOperationType__c.label
            );

            System.assertEquals(
                'Account',
                eachSubject.SobjectName__c,
                Schema.SObjectType.DmlOperationSubject__c.fields.SobjectName__c.label
            );
        }

        // Assert all expected accounts are captured in the tracked subjects
        System.assertEquals(
            accounts.size(),
            subjectIdSet.size(),
            'number of accounts and number of subjects should match'
        );

        for (Account eachAccount : accounts) {
            System.assert(
                subjectIdSet.contains(eachAccount.Id),
                'Subjects must contain Account ID ' + eachAccount.Id
            );
        }
    }
}