src/objects/MergeResultFieldMapping__mdt.object
<CustomObject>
    <description>This metadata maps a field from an object (e.g., Account, Contact) to a field on the Merge Result record that would be created when records are merged in that object</description>
    <fields>
        <fullName>FieldName__c</fullName>
        <description>The full API name (including &quot;__c&quot; for custom fields) of the field under consideration</description>
        <inlineHelpText>The full API name (including &quot;__c&quot; for custom fields) of the field under consideration</inlineHelpText>
        <label>Field Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ResultFieldEnding__c</fullName>
        <description>The unique ending (including &quot;__c&quot; for custom fields) of the target Merge Result field in which the value from the involved record should be stored. This is used to derive the appropriate `EffectiveMasterRecord`, `MasterRecord` and `MergedRecord` fields.</description>
        <inlineHelpText>The unique ending (including &quot;__c&quot; for custom fields) of the target Merge Result field</inlineHelpText>
        <label>Result Field Ending</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Merge Result Field Mapping</label>
    <pluralLabel>Merge Result Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/classes/MergeResultServiceTest.cls
@isTest
private class MergeResultServiceTest {

    @isTest
    private static void getAccountFieldMappings() {

        // Given
        MergeResultService service =
                MergeResultService.getInstance(Account.sobjectType);

        // When
        Test.startTest();

        List<MergeResultFieldMapping__mdt> mappings =
                service.getFieldMappings();

        // Then
        Test.stopTest();

        // Look through the mappings for one that maps the native `Id`
        // field to the `Id__c` field ending
        MergeResultFieldMapping__mdt idMapping = null;

        for (MergeResultFieldMapping__mdt eachMapping : mappings) {
            if (eachMapping.FieldName__c == 'Id'
                    && eachMapping.ResultFieldEnding__c == 'Id__c') {
                idMapping = eachMapping;
            }
        }

        System.assert(idMapping != null, 'Account ID mapping not found!');
    }

    @isTest
    private static void getContactFieldMappings() {

        // Given
        MergeResultService service =
                MergeResultService.getInstance(Contact.sobjectType);

        // When
        Test.startTest();

        List<MergeResultFieldMapping__mdt> mappings =
                service.getFieldMappings();

        // Then
        Test.stopTest();

        // Look through the mappings for one that maps the native `Id`
        // field to the `Id__c` field ending
        MergeResultFieldMapping__mdt idMapping = null;

        for (MergeResultFieldMapping__mdt eachMapping : mappings) {
            if (eachMapping.FieldName__c == 'Id'
                    && eachMapping.ResultFieldEnding__c == 'Id__c') {
                idMapping = eachMapping;
            }
        }

        System.assert(idMapping != null, 'Contact ID mapping not found!');
    }
}