src/objects/MergeResultFieldMapping__mdt.object
<CustomObject>
    <description>This metadata maps a field from an object (e.g., Account, Contact) to a field on the Merge Result record that would be created when records are merged in that object</description>
    <fields>
        <fullName>FieldName__c</fullName>
        <description>The full API name (including &quot;__c&quot; for custom fields) of the field under consideration</description>
        <inlineHelpText>The full API name (including &quot;__c&quot; for custom fields) of the field under consideration</inlineHelpText>
        <label>Field Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ResultFieldEnding__c</fullName>
        <description>The unique ending (including &quot;__c&quot; for custom fields) of the target Merge Result field in which the value from the involved record should be stored. This is used to derive the appropriate `EffectiveMasterRecord`, `MasterRecord` and `MergedRecord` fields.</description>
        <inlineHelpText>The unique ending (including &quot;__c&quot; for custom fields) of the target Merge Result field</inlineHelpText>
        <label>Result Field Ending</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SobjectName__c</fullName>
        <description>The full API name (including &quot;__c&quot; for custom objects) of the object on which the field exists</description>
        <inlineHelpText>The full API name (including &quot;__c&quot; for custom objects) of the object on which the field exists</inlineHelpText>
        <label>Object Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Merge Result Field Mapping</label>
    <pluralLabel>Merge Result Field Mappings</pluralLabel>
</CustomObject>

src/classes/MergeResultService.cls
global with sharing class MergeResultService {

    private static Map<String, MergeResultService> instanceMap =
            new Map<String, MergeResultService>();

    private String objectName;

    global MergeResultService(String objectName) {
        this.objectName = objectName;
    }

    global List<MergeResultFieldMapping__mdt> getFieldMappings() {
        return [
            SELECT FieldName__c, ResultFieldEnding__c
            FROM MergeResultFieldMapping__mdt
            WHERE SobjectName__c = :this.objectName
        ];
    }

    global static MergeResultService getInstance(SObjectType objectType) {
        return getInstance(objectType.getDescribe().getName());
    }

    global static MergeResultService getInstance(String objectName) {
        if (!instanceMap.containsKey(objectName)) {
            instanceMap.put(objectName, new MergeResultService(objectName));
        }

        return instanceMap.get(objectName);
    }
}