src/objects/MergeResult__c.object
<CustomObject>
    <description>The result of a merge operation, containing information that would enable an admin to undo the operation if desired</description>
    <label>Merge Result</label>
    <nameField>
        <displayFormat>MR-{00000000}</displayFormat>
        <label>Merge Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merge Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MergeResult__c/fields/SobjectName__c.field-meta.xml
<CustomField>
    <fullName>SobjectName__c</fullName>
    <description>The full API name (including &quot;__c&quot; for custom objects) of the object on which the field exists</description>
    <inlineHelpText>The full API name (including &quot;__c&quot; for custom objects) of the object on which the field exists</inlineHelpText>
    <label>Object Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/objects/MergeResultFieldMapping__mdt.object
<CustomObject>
    <description>This metadata maps a field from an object (e.g., Account, Contact) to a field on the Merge Result record that would be created when records are merged in that object</description>
    <fields>
        <fullName>FieldName__c</fullName>
        <description>The full API name (including &quot;__c&quot; for custom fields) of the field under consideration</description>
        <inlineHelpText>The full API name (including &quot;__c&quot; for custom fields) of the field under consideration</inlineHelpText>
        <label>Field Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ResultFieldEnding__c</fullName>
        <description>The unique ending (including &quot;__c&quot; for custom fields) of the target Merge Result field in which the value from the involved record should be stored. This is used to derive the appropriate `EffectiveMasterRecord`, `MasterRecord` and `MergedRecord` fields.</description>
        <inlineHelpText>The unique ending (including &quot;__c&quot; for custom fields) of the target Merge Result field</inlineHelpText>
        <label>Result Field Ending</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SobjectName__c</fullName>
        <description>The full API name (including &quot;__c&quot; for custom objects) of the object on which the field exists</description>
        <inlineHelpText>The full API name (including &quot;__c&quot; for custom objects) of the object on which the field exists</inlineHelpText>
        <label>Object Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Merge Result Field Mapping</label>
    <pluralLabel>Merge Result Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/classes/MergeResultService.cls
global with sharing class MergeResultService {

    private static Map<String, MergeResultService> instanceMap =
            new Map<String, MergeResultService>();

    private String objectName;

    global MergeResultService(String objectName) {
        this.objectName = objectName;
    }

    global List<MergeResultFieldMapping__mdt> getFieldMappings() {
        return [
            SELECT FieldName__c, ResultFieldEnding__c
            FROM MergeResultFieldMapping__mdt
            WHERE SobjectName__c = :this.objectName
        ];
    }

    global static MergeResultService getInstance(SObjectType objectType) {
        return getInstance(objectType.getDescribe().getName());
    }

    global static MergeResultService getInstance(String objectName) {
        if (!instanceMap.containsKey(objectName)) {
            instanceMap.put(objectName, new MergeResultService(objectName));
        }

        return instanceMap.get(objectName);
    }

    global String getMasterRecordQuery(List<String> fieldNames) {
        List<String> queryParts = new List<String> {
            'SELECT ' + String.join(fieldNames, ', '),
            'FROM ' + this.objectName,
            'WHERE Id = :recordId'
        };

        return String.join(queryParts, ' ');
    }

    global Sobject getMasterRecord(Sobject mergedRecord) {

        // Get the record ID for the master record
        Id recordId = (Id)mergedRecord.get('MasterRecordId');

        // Return the result of the dynamic query for the master record,
        // a query which is assumed to always succeed
        List<String> fieldNames = new List<String>(
                mergedRecord.getSObjectType().getDescribe().fields.getMap().keySet());

        fieldNames.sort();

        return Database.query(getMasterRecordQuery(fieldNames));
    }

    global MergeResult__c getMergeResult(Sobject mergedRecord) {

        // Get the master record
        Sobject masterRecord = this.getMasterRecord(mergedRecord);

        // Construct the merge result
        MergeResult__c result = MergeResultUtil.newMergeResult(
                masterRecord, mergedRecord, this.getFieldMappings());

        // Return the contructed merge result
        return result;
    }
}