src/objects/MergeResult__c.object
<CustomObject>
    <description>The result of a merge operation, containing information that would enable an admin to undo the operation if desired</description>
    <fields>
        <fullName>MasterRecordId__c</fullName>
        <description>The Salesforce ID of the master record</description>
        <inlineHelpText>The Salesforce ID of the master record</inlineHelpText>
        <label>Master Record ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MergedRecordId__c</fullName>
        <description>The Salesforce ID of the merged record</description>
        <inlineHelpText>The Salesforce ID of the merged record</inlineHelpText>
        <label>Merged Record ID</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Merge Result</label>
    <nameField>
        <displayFormat>MR-{00000000}</displayFormat>
        <label>Merge Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merge Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountMergeResultTriggerTest.cls
@isTest
private class AccountMergeResultTriggerTest {

    @isTest
    private static void mergeAccounts() {

        // Given
        Account acme = [
            SELECT Id
            FROM Account
            WHERE Name = 'Acme Corporation (TEST)'
        ];

        Account marvel = [
            SELECT Id
            FROM Account
            WHERE Name = 'Marvel Universe (TEST)'
        ];

        // When
        Test.startTest();

        merge acme marvel;

        // Then
        Test.stopTest();

        MergeResult__c result = [
            SELECT Id, MasterRecordId__c, MergedRecordId__c
            FROM MergeResult__c
            WHERE MergedRecordId__c = :marvel.Id
        ];

        System.assertEquals(acme.Id, result.MasterRecordId__c,
                Schema.MergeResult__c.fields.MasterRecordId__c.getDescribe().label);
    }

    @testSetup
    private static void setup() {

        // Create accounts
        Account acme = new Account(
                Name = 'Acme Corporation (TEST)');

        Account marvel = new Account(
                Name = 'Marvel Universe (TEST)');

        insert new List<Account> { acme, marvel };
    }
}