src/objects/MergeResult__c.object
<CustomObject>
    <description>The result of a merge operation, containing information that would enable an admin to undo the operation if desired</description>
    <fields>
        <fullName>MasterRecordBody__c</fullName>
        <description>JSON representing the master record before the merge operation was initiated</description>
        <inlineHelpText>JSON representing the master record before the merge operation was initiated</inlineHelpText>
        <label>Master Record Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MergedRecordBody__c</fullName>
        <description>JSON representing the merged record before the merge operation was initiated</description>
        <inlineHelpText>JSON representing the merged record before the merge operation was initiated</inlineHelpText>
        <label>Merged Record Body</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Merge Result</label>
    <nameField>
        <displayFormat>MR-{00000000}</displayFormat>
        <label>Merge Result Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merge Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MergeResult__c/fields/SobjectName__c.field-meta.xml
<CustomField>
    <fullName>SobjectName__c</fullName>
    <description>The full API name (including &quot;__c&quot; for custom objects) of the object on which the field exists</description>
    <inlineHelpText>The full API name (including &quot;__c&quot; for custom objects) of the object on which the field exists</inlineHelpText>
    <label>Object Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/objects/MergeResultFieldMapping__mdt.object
<CustomObject>
    <description>This metadata maps a field from an object (e.g., Account, Contact) to a field on the Merge Result record that would be created when records are merged in that object</description>
    <fields>
        <fullName>FieldName__c</fullName>
        <description>The full API name (including &quot;__c&quot; for custom fields) of the field under consideration</description>
        <inlineHelpText>The full API name (including &quot;__c&quot; for custom fields) of the field under consideration</inlineHelpText>
        <label>Field Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ResultFieldEnding__c</fullName>
        <description>The unique ending (including &quot;__c&quot; for custom fields) of the target Merge Result field in which the value from the involved record should be stored. This is used to derive the appropriate `EffectiveMasterRecord`, `MasterRecord` and `MergedRecord` fields.</description>
        <inlineHelpText>The unique ending (including &quot;__c&quot; for custom fields) of the target Merge Result field</inlineHelpText>
        <label>Result Field Ending</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SobjectName__c</fullName>
        <description>The full API name (including &quot;__c&quot; for custom objects) of the object on which the field exists</description>
        <inlineHelpText>The full API name (including &quot;__c&quot; for custom objects) of the object on which the field exists</inlineHelpText>
        <label>Object Name</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Merge Result Field Mapping</label>
    <pluralLabel>Merge Result Field Mappings</pluralLabel>
</CustomObject>

force-app/main/default/classes/MergeResultUtil.cls
global with sharing class MergeResultUtil {

    global static final String EFFECTIVE_MASTER_RECORD_PREFIX =
            'EffectiveMasterRecord';

    global static final String MASTER_RECORD_PREFIX = 'MasterRecord';

    global static final String MERGED_RECORD_PREFIX = 'MergedRecord';

    global static MergeResult__c newMergeResult(
            Sobject masterRecord, Sobject mergedRecord,
            List<MergeResultFieldMapping__mdt> mappings) {

        // Initialize the result with the bodies of each record
        MergeResult__c result = new MergeResult__c(
                SobjectName__c = masterRecord.getSObjectType().getDescribe().getName(),
                MasterRecordBody__c = JSON.serialize(masterRecord),
                MergedRecordBody__c = JSON.serialize(mergedRecord));

        // Store the notable values of interest to track
        for (MergeResultFieldMapping__mdt eachMapping : mappings) {

            // Figure out the expected field names
            String masterRecordFieldName =
                    MASTER_RECORD_PREFIX
                            + eachMapping.ResultFieldEnding__c;

            // Figure out the expected field names
            String mergedRecordFieldName =
                    MERGED_RECORD_PREFIX
                            + eachMapping.ResultFieldEnding__c;

            // Store the field values
            result.put(masterRecordFieldName, String.valueOf(
                    masterRecord.get(eachMapping.FieldName__c)));

            result.put(mergedRecordFieldName, String.valueOf(
                    mergedRecord.get(eachMapping.FieldName__c)));
        }

        return result;
    }
}